version: "3.9"

services:
  gamexon-rec:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/gamexon-cafe
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
